"""sync models

Revision ID: e9b2f87d326f
Revises: 71bcc9c08d08
Create Date: 2026-04-14 16:36:30.041103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9b2f87d326f'
down_revision: Union[str, Sequence[str], None] = '71bcc9c08d08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_listings', sa.Column('region', sa.String(), nullable=True))
    op.add_column('property_listings', sa.Column('county', sa.String(), nullable=True))
    op.add_column('property_listings', sa.Column('property_number', sa.String(), nullable=True))
    op.add_column('property_listings', sa.Column('title_number', sa.String(), nullable=True))
    op.add_column('property_listings', sa.Column('price', sa.String(), nullable=True))
    op.add_column('property_listings', sa.Column('commission', sa.String(), nullable=True))
    op.add_column('property_listings', sa.Column('contract_duration', sa.String(), nullable=True))
    op.create_index(op.f('ix_property_listings_title_number'), 'property_listings', ['title_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_property_listings_title_number'), table_name='property_listings')
    op.drop_column('property_listings', 'contract_duration')
    op.drop_column('property_listings', 'commission')
    op.drop_column('property_listings', 'price')
    op.drop_column('property_listings', 'title_number')
    op.drop_column('property_listings', 'property_number')
    op.drop_column('property_listings', 'county')
    op.drop_column('property_listings', 'region')
    # ### end Alembic commands ###
